# local data loaders
height: 112
width: 112
seq_len: 16
train_bz: 16
test_bz: 8
num_workers: 4

# network architecture
arch: 'mobilenet3d_v2'
width_mult: 0.45 
num_classes: 12
pretrained_model: 'pre-trained/kinetics_mobilenetv2_0.45x_RGB_16_best.pth'

# local training
local_e: 3
epochs: 30
loss: 'CrossEntropyLoss'
optimizer: 'SGD'
lr: 0.0003
print_freq: 10

# federated learning setting 
FL: 'FedAvg'
frac: 1 # participation ratio
num_C: 4 # client number
min_sample_size: 2
min_num_clients: 2 
seed: 1234 
device: 'cuda'

