local_e: 1 # local epoch
epochs: 100 # communication rounds
device: 'cuda' # GPU or not
batch_size: 32 # local batch size
dataset: 'gld23k' 
model: 'MobileNetV3'
optimizer: 'Adam'
lr: 0.001 # learning rate 
frac: 1 # partipation ratio
num_C: 5 # client number
min_sample_size: 2
min_num_clients: 2 
seed: 1234 
