local_e: 1 # local epoch
epochs: 100 # communication rounds
batch_size: 16 # local batch size
dataset: 'hmdb51' 
fold: 1
frac: 1 # partipation ratio
num_C: 5 # client number
min_sample_size: 2
min_num_clients: 2 
seed: 1234 